name: Deploy Vulnerable App to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image
        run: |
          heroku_app_name=pedro-app-vulnerable2022
          docker build -t registry.heroku.com/$heroku_app_name/web .
          docker push registry.heroku.com/$heroku_app_name/web

      - name: Release Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku_app_name=pedro-app-vulnerable2022
          IMAGE_ID=$(docker inspect registry.heroku.com/$heroku_app_name/web --format={{.Id}})
          curl -n -X PATCH https://api.heroku.com/apps/$heroku_app_name/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'"$IMAGE_ID"'"
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
