name: Gitleaks Secret Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gitleaks-scan:
    name: Scan secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --verbose --redact --exit-code=1
