name: Trivy Vulnerability Scanner

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  trivy-scan:
    name: Trivy Full Scan (Code + Docker Image)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan project files (filesystem)
        run: |
          echo "📂 Scanning project files (code, secrets, IaC)..."
          trivy fs . --exit-code 1 --severity HIGH,CRITICAL --no-progress

      - name: Scan Docker image
        run: |
          echo "🐳 Scanning Docker image..."
          trivy image myapp:latest --exit-code 1 --severity HIGH,CRITICAL --no-progress
